# https://taskfile.dev

version: '3'


tasks:
  build:
    desc: Build for Docker Hub
    cmds:
      - docker buildx build -t alastairhm/alpine-jekyll:latest ./
    silent: true
  push:
    desc: Push to Docker Hub
    cmds:
      - docker push alastairhm/alpine-jekyll:latest
    silent: true
  create:
    desc: Create a new blog
    cmds:
      - docker run -it -p 8080:80  -v $PWD/blog:/blog alastairhm/alpine-jekyll /create.sh mysite
    silent: true
  test:
    desc: Test a new blog
    cmds:
      - docker run -it -p 8080:80 -v $PWD/blog/mysite:/blog alastairhm/alpine-jekyll
    silent: true
